select cn9_numero NUMERO,cn9_revisa REVISAO, cn9_xtpmdl CODIGO_MODALIDADE, (SELECT  ZZM_DESCRI FROM ZZM010 WHERE CN9010.CN9_XTPMDL = ZZM_CODIGO AND ZZM010.D_E_L_E_T_ = ' ' AND CN9010.D_E_L_E_T_ = ' ') AS DESCRICA_MODALIDADE 
from cn9010
where cn9010.d_e_l_e_t_ = ' '

