CREATE TABLE PCOMETA010(
  META_CODIGO VARCHAR(5) NOT NULL,
  META_DESCRI VARCHAR(250) NOT NULL
);

CREATE TABLE PCOPRODUTO010 (
  PRODUTO_CODIGO VARCHAR(5) NOT NULL,
  PRODUTO_DESCRI VARCHAR(250) NOT NULL
);



CREATE TABLE PCOSETOR010 (
  SETOR_CODIGO VARCHAR(5) NOT NULL,
  SETOR_DESCRI VARCHAR(250) NOT NULL
);


CREATE TABLE PCOCOMPLEX010 (
  COMPLEX_CODIGO VARCHAR(2) NOT NULL,
  COMPLEX_DESCRI VARCHAR(250) NOT NULL
);


DROP TABLE PCOCOMPLEX010


COMMIT