INSERT INTO PCOMETA010 (META_CODIGO, META_DESCRI) VALUES('01.01','OBJ1 INDICADOR - Taxa  de  crescimentoda  base  de  seguidores  nos  canais  da  Apex-Brasil  nas  redes sociais');
INSERT INTO PCOMETA010 (META_CODIGO, META_DESCRI) VALUES('01.02','OBJ1 META PROJETO - Reforçar o posicionamento do Brasil como parceiro global de negócios');
INSERT INTO PCOMETA010 (META_CODIGO, META_DESCRI) VALUES('01.03','OBJ1 META PROJETO - Liderar a Participação brasileira em Exposições Universais');
INSERT INTO PCOMETA010 (META_CODIGO, META_DESCRI) VALUES('02.01','OBJ2 INDICADOR - Número de empresas atendidas em inteligência de mercado');
INSERT INTO PCOMETA010 (META_CODIGO, META_DESCRI) VALUES('02.02','OBJ2 META PROJETO - Construir metodologia sólida de avaliação de satisfação dos produtos de inteligência da Apex');
INSERT INTO PCOMETA010 (META_CODIGO, META_DESCRI) VALUES('03.01','OBJ3 INDICADOR - Percentual de novas empresas atendidas no portfólio de qualificação');
INSERT INTO PCOMETA010 (META_CODIGO, META_DESCRI) VALUES('03.02','OBJ3 INDICADOR - Percentual de empresas qualificadas e incorporadas ao portfólio de promoção e internacionalização');
INSERT INTO PCOMETA010 (META_CODIGO, META_DESCRI) VALUES('03.03','OBJ3 META PROJETO - Estruturar o programa de e-commerce, abrangendo sensibilização, mentoria e promoção comercial');
INSERT INTO PCOMETA010 (META_CODIGO, META_DESCRI) VALUES('03.04','OBJ3 META PROJETO - Estruturar o programa para ECEX');
INSERT INTO PCOMETA010 (META_CODIGO, META_DESCRI) VALUES('04.01','OBJ4 INDICADOR - Percentual de empresas exportadoras brasileiras apoiadas pela Apex-Brasil');
INSERT INTO PCOMETA010 (META_CODIGO, META_DESCRI) VALUES('04.02','OBJ4 INDICADOR - Número de abertura ou plano de abertura de novas operações no exterior');
INSERT INTO PCOMETA010 (META_CODIGO, META_DESCRI) VALUES('05.01','OBJ5 INDICADOR - Número de Projetos de Investimentos Facilitados');
INSERT INTO PCOMETA010 (META_CODIGO, META_DESCRI) VALUES('05.02','OBJ5 INDICADOR - Número de atendimentos a investidores qualificados');
INSERT INTO PCOMETA010 (META_CODIGO, META_DESCRI) VALUES('06.01','OBJ6 INDICADOR - Representatividade da Apex-Brasil no Congresso Nacional');
INSERT INTO PCOMETA010 (META_CODIGO, META_DESCRI) VALUES('06.02','OBJ6 META PROJETO - Estabelecer  parcerias e vínculos de confiança com stakeholders');
INSERT INTO PCOMETA010 (META_CODIGO, META_DESCRI) VALUES('06.03','OBJ6 META PROJETO - Apoiar  ações  de alinhamento  e  integração ao MRE');
INSERT INTO PCOMETA010 (META_CODIGO, META_DESCRI) VALUES('07.01','OBJ7 META PROJETO - Estruturação da Estratégia do Relacionamento com Clientes da Apex-Brasil');
INSERT INTO PCOMETA010 (META_CODIGO, META_DESCRI) VALUES('07.02','OBJ7 META PROJETO - Estruturação da Gestão do Relacionamento com CRM');
INSERT INTO PCOMETA010 (META_CODIGO, META_DESCRI) VALUES('08.01','OBJ8 META PROJETO - Desenvolver a Plataforma Digital Multicanal da Apex-Brasil');
INSERT INTO PCOMETA010 (META_CODIGO, META_DESCRI) VALUES('08.02','OBJ8 META PROJETO - Implantar a Cultura de Inovação na Apex-Brasil');
INSERT INTO PCOMETA010 (META_CODIGO, META_DESCRI) VALUES('09.01','OBJ9  INDICADOR- Quantidade média de horas de capacitação por colaborador');
INSERT INTO PCOMETA010 (META_CODIGO, META_DESCRI) VALUES('09.02','OBJ9 META PROJETO - Obter a certificação Great Place to Work');
INSERT INTO PCOMETA010 (META_CODIGO, META_DESCRI) VALUES('10.01','OBJ10 META PROJETO - Evoluir para o nível  3 do Programa de Compliance');
INSERT INTO PCOMETA010 (META_CODIGO, META_DESCRI) VALUES('10.02','OBJ10 META PROJETO - Assegurar que a Apex estará preparada para a Certificação ISO 9001 até 2023');
INSERT INTO PCOMETA010 (META_CODIGO, META_DESCRI) VALUES('11.01','OBJ11 INDICADOR - Percentual de execução do PDTIC');
INSERT INTO PCOMETA010 (META_CODIGO, META_DESCRI) VALUES('11.02','OBJ11 META PROJETO - Implantar e executar o processo de gestão de serviços de TIC');
INSERT INTO PCOMETA010 (META_CODIGO, META_DESCRI) VALUES('12.01','OBJ12 INDICADOR - Taxa de crescimento da receita gerada com produtos e serviços');
INSERT INTO PCOMETA010 (META_CODIGO, META_DESCRI) VALUES('12.02','OBJ12 INDICADOR - Índice de sustentabilidade das receitas próprias da Apex-Brasil');
INSERT INTO PCOMETA010 (META_CODIGO, META_DESCRI) VALUES('12.03','OBJ12 INDICADOR - Percentual do Teto de Custeio Administrativo');
INSERT INTO PCOMETA010 (META_CODIGO, META_DESCRI) VALUES('12.04','OBJ12 INDICADOR - Percentual do Teto de Despesa de PessoalV');
INSERT INTO PCOMETA010 (META_CODIGO, META_DESCRI) VALUES('00.00','Não se Aplica');
