INSERT INTO PCOCOMPLEX010 (COMPLEX_DESCRI,COMPLEX_CODIGO) VALUES('Alimentos_Bebidas_Agronegócios','01');

INSERT INTO PCOCOMPLEX010 (COMPLEX_DESCRI,COMPLEX_CODIGO) VALUES('Casa_e_construção','02');

INSERT INTO PCOCOMPLEX010 (COMPLEX_DESCRI,COMPLEX_CODIGO) VALUES('Economia_Criativa_e_Serviços','03');

INSERT INTO PCOCOMPLEX010 (COMPLEX_DESCRI,COMPLEX_CODIGO) VALUES('Máquinas_e_Equipamentos','04');

INSERT INTO PCOCOMPLEX010 (COMPLEX_DESCRI,COMPLEX_CODIGO) VALUES('Moda','05');

INSERT INTO PCOCOMPLEX010 (COMPLEX_DESCRI,COMPLEX_CODIGO) VALUES('Tecnologia_e_Saúde','06');

INSERT INTO PCOCOMPLEX010 (COMPLEX_DESCRI,COMPLEX_CODIGO) VALUES('Atração_Investimentos','07');

INSERT INTO PCOCOMPLEX010 (COMPLEX_DESCRI,COMPLEX_CODIGO) VALUES('MultisCOMPLEXial','08');

INSERT INTO PCOCOMPLEX010 (COMPLEX_DESCRI,COMPLEX_CODIGO) VALUES('Não_se_aplica','00');

SELECT * FROM PCOCOMPLEX010

COMMIT